// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210304091446_UserPasswordAdded")]
    partial class UserPasswordAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Entities.MstrAgents", b =>
                {
                    b.Property<int>("idAgents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("bActive")
                        .HasColumnType("int");

                    b.Property<string>("cAgentName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("cDescription")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("cEmail")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("cPassword")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<byte>("iCategoryLevel")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("passwordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("idAgents");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("API.Entities.MstrBuyer", b =>
                {
                    b.Property<int>("AutoIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyerCompanyCode")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CompanyShortName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("AutoIdx");

                    b.ToTable("Master.Buyer");
                });

            modelBuilder.Entity("API.Entities.MstrDivision", b =>
                {
                    b.Property<int>("AutoIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AutoIdx");

                    b.ToTable("Master.Division");
                });

            modelBuilder.Entity("API.Entities.MstrProduct", b =>
                {
                    b.Property<int>("AutoIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AutoIdx");

                    b.ToTable("Master.Product");
                });

            modelBuilder.Entity("API.Entities.MstrSeason", b =>
                {
                    b.Property<int>("AutoIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AutoIdx");

                    b.ToTable("Master.Season");
                });

            modelBuilder.Entity("API.Entities.MstrStyle", b =>
                {
                    b.Property<int>("AutoIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuyersAutoIdx")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Link_BuyerId")
                        .HasColumnType("int");

                    b.Property<int>("Link_ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductsAutoIdx")
                        .HasColumnType("int");

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AutoIdx");

                    b.HasIndex("BuyersAutoIdx");

                    b.HasIndex("ProductsAutoIdx");

                    b.ToTable("Master.Style");
                });

            modelBuilder.Entity("API.Entities.MstrStyle", b =>
                {
                    b.HasOne("API.Entities.MstrBuyer", "Buyers")
                        .WithMany("Styles")
                        .HasForeignKey("BuyersAutoIdx");

                    b.HasOne("API.Entities.MstrProduct", "Products")
                        .WithMany("Styles")
                        .HasForeignKey("ProductsAutoIdx");
                });
#pragma warning restore 612, 618
        }
    }
}
